import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :mmo, MMOWeb.Endpoint,
  env: System.get_env("MIX_ENV"),
  # cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: "2CJ0/N1O9aus9QXplrTFMzOvngUCMWkUsv6t7q0Pnlohqo9xCrPHdZGPAEgnsXqC",
  url: [
    host: System.get_env("PORTAL_HOST") || "mmo.k8s.el8.nl",
    port: 443,
    scheme: "https"
  ],
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    protocol_options: [
      max_header_name_length: 64,
      max_header_value_length: 8192,
      max_headers: 100
    ]
  ],
  pubsub_server: MMO.PubSub,
  # pubsub: [name: MMO.PubSub, adapter: Phoenix.PubSub.PG2],
  # instrumenters: [MMOWeb.Endpoint.PhoenixInstrumenter]
  live_view: [
    signing_salt: System.get_env("SIGNING_SALT")
  ],
  check_origin: false,
  server: true,
  root: ".",
  version: Application.spec(:mmo, :vsn)

# Do not print debug messages in production
config :logger, level: :info

# Strip out personal data in production
config :phoenix, :filter_parameters, [
  "password",
  "password_confirmation",
  "first_name",
  "last_name",
  "phone",
  "email"
]

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :mmo, MMOWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :mmo, MMOWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.
